github: [metadata]
encoding: UTF-8
kramdown:
   input: GFM
   hard_wrap: false
future: true
jailed: false
remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
gfm_quirks: paragraph_end
author: <a rel="me" href="https://fosstodon.org/@hraefn">Nathan Stilwell</a>